# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0008_auto_20180329_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
